INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('BE', 'Insulated car having ice bunkers or ice boxes and ventilators. Chunk ice used mainly.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('BM', 'Non-refrigerated car used mainly in passenger trains to carry milk in cans or bottles.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('BMK', 'Insulated car having ice bunkers or ice boxes, otherwise same as Class BM.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('BMT', 'Carries precooled bulk milk in large insulated tanks. No refrigeration.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('BP', 'Insulated car having no vents but refrigerated.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('BS', 'Refrigerator having brine tanks and using salt with crushed ice.  Used mainly for meats and packing house products. Very few have vents.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('BX', 'Box car equipped for service in passenger train, i.e., having steam lines, air, and communication hoses.  Used mainly in express service. Has sliding box car type doors and is made with or without windows.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('FB', 'Car havinga skeleton framework for carrying barrels.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('FC', 'Flat car for carrying highway trailers exclusively.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('FD', 'Flat car havinga depressed center for loadings of extreme clearances.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('FG', 'Designed for military guns or other extremely heavy loadings');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('FL', 'Special car having 2 trucks connected witha flexible frame and fitted with cross braces above bolsters.  Logs are loaded on the cross supports lengthways.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('FM', 'Ordinary flat car having flooring laid over the sills and without sides or ends.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('FW', 'Well hole car for loads needing stability as well as extra clearance.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('GA', 'Has drop bottom and fixed ends and sides. Bottom is hinged crosswise of the car to dump between rails.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('GB', ' Open top car: has fixed sides, fixed or drop ends, and solid bottom. Suitable for mill trade. Most are fifty five or more feet in length.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('GE', 'Same as Class GA except for drop ends instead of solid ends.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('GH', 'Has drop ends, drop bottom, and is hinged at center sill for dumping outside the rails.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('GT', 'Same as Class GB except for solid ends, and is suitable for dumping machinery only when used in the coal trade.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('GRA', 'Has fixed sides, ends, and bottoms, but has one or more hoppers to dump outside the rails.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('GS', 'The same as Class GH except for solid ends.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('GT', 'Same as Class GB except for solid ends, and is suitable for dumping machinery only when used in the coal trade.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('HD', 'Same as Class HE except doors are hinged to dump outside the rails. (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('HE', 'Not a self-clearing car. Has level bottom, hinged crossways to dump between the rails. (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('HF', 'Same as Class HM except for hoppers extending from the end of the car over the bolsters, with doors hinged lengthwise of car, to dump outside the rails. (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('HFA', 'Same as Class HMA except for the hopper doors in ends, as in Class HF. ®');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('HFB', 'An open top, self-clearing hopper with doors hinged lengthwise of car. Has cross hoppers at ends of car with doors to dump either between, or between and outside the rails while center hoppers dump outside the rails. (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('HK', 'Same as Class HE except can dump either inside or outside the rails. (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('HM', 'Self-clearing, open top car with fixed sides and ends. Bottom has two hoppers with doors hinged crosswise of car to dump between rails.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('HMA', 'Same as Class HM except doors are hinged lengthwise to dump between rails.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('LC', 'House car with side doors and roof hatches. May or may not have end doors. (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('LE', 'House car with high, sliding doors (like Class XM).  Lower half of sides may have two or more doors hinged to open outward--such as tool compartments.  (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('LFA', 'Flat car with containers to carry items of commerce immersed in a liquid (such as Phosphorus).');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('LO', 'Covered hopper, self-clearing, enclosed car with roof hatches or doors. Weathertight around all openings. May or may not have sealable, waterproof doors or valves in bottom for unloading.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('LP', 'Flat car having sides like a box car but ends are solid or slatted. With or without runningboards having guard rails. Used for pulpwood loading.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('LRC', 'Box car with heavily insulated floor and sides and partly insulated ends. With or without gravity conveyors. Sometimes used for solid carbon dioxide loadings.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('LT', 'Enclosed car having a round body and sealable weathertight doors and top opening. Bottom opening fitted internally with mechanical means for unloading. Used for very special loadings of dry or granulated commodities. (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('LTA', 'Same as Class LT except no mechanical unloader. (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('MT', 'Same as Class HM except has three or more hoppers.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('NE', 'Eight-wheel caboose with sleeping quarters for the men and storage space for tools, lights, etc. Some of the newer ones have radios, electric lights, and bay windows instead of cupolas.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('RA', 'Fully insulated but has brine tanks  instead of bunkers. Usually has no vents and uses crushed ice and/or salt.  Used for carrying meat.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('RB', 'Similar to Class RS but not equipped with bunkers and vents.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('RC', 'Car equipped with two or more fully insulated demountable containers.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('RCD', 'Insulated car with or without vents, with a refrigeration system using mainly carbon dioxide. Mainly used for shipping bananas.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('RS', 'Fully insulated reefer with ice bunkers used mainly with chunk ice. May or may not be vented.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('RSM', 'Similar to Class RS except has beef rails as well as bunkers.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('SC', 'Similar to Class SM except that it may be either single or double decked, convertible.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('SD', 'Drop bottom car for easy cleaning. May be either single or double deck.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('SE', 'Same as Class SM except fora floor half way between the normal floor and the roof. Commonly called "doubledecker."');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('SH', 'Palace Horse Car of the Gay Nineties. Resembles a baggage car more thana stock car, but has stalls and ventilation. (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('SM', 'House car with solid ends and slatted walls, having one solid floor for carrying cattle');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('SP', 'Walls consist of wire screening and ends are solid.  Center section usually has compartment for an attendant.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('SPR', 'Poultry and refrigerator car combined. One end carries live poultry and other end carries frozen poultry. Caretaker''s compartment in the middle. (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('TA', 'Tank having no bottom discharge pipe and used for acid loading only.  Siphon loading and unloading at the top.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('TG', 'Tank with a glass lining for milk or edible items.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('TGB', 'Car equipped with two cylindrical uninsulated metal tanks with or without special linings. Has cab between tanks for protecting loading valves.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('TL', 'Has special corrosion resistant linings for specified loads such as rubber, tin, zinc, lead, varnish (any except glass lining). Lining depends on commodity carried.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('TM', 'Unlined and uninsulated tank car with ICC required safety valves for general use as a carrier of liquid or oily commodities. All have bottom discharge valves.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('TMN', 'Special loading tank. Usuallya Class GT gondola with special upright, removable steel containers for liquid or granulated items. Most cars have from six to ten containers to load or remove from car by crane.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('TMU', 'Flat car having cradles for tanks of compressed liquids, or liquefied gasses. (R)');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('TW', 'Steel or wood tanks ona car. May or may not have roof over tanks or tubs. Lined or unlined.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('VA', 'Ventilated fruit and vegetable box. Equipped with ventilating ports in ends or sides, and not insulated.  Otherwise, same as Class XM.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('VAS', 'Similar to Class VA except that it is totally insulated.  May have either single or double doors but when double doors are present, half is solid door and half is screened.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('VS', 'Similar to Class VA except for floor insulation.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('VT', 'Same as Class XM except cars contain tanks for liquid shipment.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('XA', 'Automobile car.  Internal height ten feet or more.  Single or double doors in the sides (with or without end doors). At least ten feet in width. Generally fifty feet in length.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('XAB', 'Same as Class XA except for height which is eight feet internally.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('XAP', 'Auto parts car. Similar to other auto box cars except is equipped with removable or permanent racks for the conveyance or storage of auto parts or bodies.');
INSERT INTO AAR_TYPE (TYPE, DESCRIPTION) VALUES ('XM', 'General use boxcar. Most are forty feet in length with single doors on either end or in either side.  May or may not have end doors. Internal height eight feet. Wood or steel construction. Not insulated.');
INSERT INTO CAR_AREA (TYPE, DESCRIPTION) VALUES ('coupler', 'Coupler');
INSERT INTO CAR_AREA (TYPE, DESCRIPTION) VALUES ('wheels', 'Car Wheels');
INSERT INTO CAR_AREA (TYPE, DESCRIPTION) VALUES ('trucks', 'Trucks');
INSERT INTO CAR_AREA (TYPE, DESCRIPTION) VALUES ('underframe', 'Car underframe');
INSERT INTO CAR_AREA (TYPE, DESCRIPTION) VALUES ('body', 'Body of car');
INSERT INTO CAR_AREA (TYPE, DESCRIPTION) VALUES ('safety appliances', 'Safety Appliances (Steps, ladders, etc.)');
INSERT INTO CAR_AREA (TYPE, DESCRIPTION) VALUES ('rfidtag', 'RFID Tag');
INSERT INTO CAR_AREA (TYPE, DESCRIPTION) VALUES ('Other', 'other than a standard area');
INSERT INTO CAR_TYPE (TYPE, DESCRIPTION) VALUES ('gondola', 'Gondola');
INSERT INTO CAR_TYPE (TYPE, DESCRIPTION) VALUES ('box', 'Box');
INSERT INTO CAR_TYPE (TYPE, DESCRIPTION) VALUES ('flat', 'Flatcar');
INSERT INTO CAR_TYPE (TYPE, DESCRIPTION) VALUES ('reefer', 'Refrigerator car');
INSERT INTO CAR_TYPE (TYPE, DESCRIPTION) VALUES ('covered hopper', 'Covered Hopper car');
INSERT INTO CAR_TYPE (TYPE, DESCRIPTION) VALUES ('tank', 'Tank car');
INSERT INTO CAR_TYPE (TYPE, DESCRIPTION) VALUES ('caboose', 'Cabin car');
INSERT INTO CAR_TYPE (TYPE, DESCRIPTION) VALUES ('hopper', 'Hopper car');
INSERT INTO COUPLER_TYPE (TYPE, DESCRIPTION) VALUES ('Kadee', 'Standard Kadee #5');
INSERT INTO COUPLER_TYPE (TYPE, DESCRIPTION) VALUES ('Sargent', 'Sargent Prototypical');
INSERT INTO KIT_TYPE (TYPE, DESCRIPTION) VALUES ('rtr', 'Ready to Run');
INSERT INTO KIT_TYPE (TYPE, DESCRIPTION) VALUES ('brass', 'High Quality Brass');
INSERT INTO KIT_TYPE (TYPE, DESCRIPTION) VALUES ('shake', 'Shake the Box');
INSERT INTO KIT_TYPE (TYPE, DESCRIPTION) VALUES ('craftsman', 'Craftsman');
INSERT INTO MANUFACTURER (MANF_NAME, DESCRIPTION) VALUES ('Other', 'Other than a manufacturer listed here');
INSERT INTO MANUFACTURER (MANF_NAME, DESCRIPTION) VALUES ('Kadee', 'Kadee');
INSERT INTO MANUFACTURER (MANF_NAME, DESCRIPTION) VALUES ('Quality Craft', 'Quality Craft');
INSERT INTO MANUFACTURER (MANF_NAME, DESCRIPTION) VALUES ('Ambroid', 'One of 5000 Kit');
INSERT INTO MANUFACTURER (MANF_NAME, DESCRIPTION) VALUES ('Westerfield', 'Manufacturer of resin car kits');
INSERT INTO MANUFACTURER (MANF_NAME, DESCRIPTION) VALUES ('Funero & Cumerlingo', 'Manufacturer of resin car kits');
INSERT INTO MANUFACTURER (MANF_NAME) VALUES ('Bowser');
INSERT INTO MANUFACTURER (MANF_NAME) VALUES ('Rapido');
INSERT INTO MANUFACTURER (MANF_NAME) VALUES ('Accurail');
